# Files/Folders to exclude from the final output
exclude:
  - .sass-cache
  - CNAME
  - config.rb
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-sitemap

sass:
  sass_dir: css

permalink: none

highlighter: rouge
markdown: kramdown
